main: Readme.md

title: Kyso Documentation

branch: master

summary:
  - Kyso Documentation: Readme.md

  - Getting started with Kyso: false
  - Kyso for data-scientists: getting-started/kyso-for-data-scientists.md
  - How to write a data-science article: getting-started/how-to-write-a-data-science-article.md
  # - Kyso for teams: getting-started/kyso-for-teams/Readme.md
  # - Kyso for scientists: getting-started/kyso-for-scientists/Readme.md

  - Posting to Kyso: false
  - Publishing to Kyso: writing-a-post-on-kyso/Readme.md
  - Connecting your Github Repositories: connect-github/Readme.md
  - Kyso's Jupyterlab extension: jupyterlab-plugin/Readme.md

  - Workspaces: false
  - Launching a workspace: starting-a-workspace/Readme.md
  - Installing additional libraries: installing-libraries/kyso-terminal.ipynb

  - Integrations: false
  - Migrating from Airbnb's knowledge repo: knowledge-repo/Readme.md

